name: Testing

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.ts.outputs.TIME }}
      date: ${{ steps.ts.outputs.DATE }}
    strategy:
      matrix:
        build-type: [mi8937, mi8917]

    steps:
      - uses: actions/checkout@v6

      - name: Timestamp
        id: ts
        run: |
          DATE=$(date +'%Y%m%d')
          TIME=$(date +'%s')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "TIME=$TIME" >> $GITHUB_OUTPUT

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc build-essential bison flex zip p7zip-full \
            libc6 curl libstdc++6 git wget libssl-dev zstd \
            lld python3

      - name: Preparing kernel sources
        run: |
          if [ -d "$PWD/android_kernel_xiaomi_msm8937" ]; then
            rm -rf android_kernel_xiaomi_msm8937
          fi
          if [[ "${{ matrix.build-type }}" == "mi8937" ]]; then
            git clone https://github.com/Mi-Thorium/kernel_msm-4.19 --depth=1 -b "lineage-21" android_kernel_xiaomi_msm8937
          elif [[ "${{ matrix.build-type }}" == "mi8917" ]]; then
            git clone https://github.com/Mi-Thorium/kernel_msm-4.19 --depth=1 -b "lineage-21" android_kernel_xiaomi_msm8937
          fi
          cp build.sh android_kernel_xiaomi_msm8937/
          chmod +x ./android_kernel_xiaomi_msm8937/build.sh

      - name: Compile the kernel
        run: |
          cd android_kernel_xiaomi_msm8937/
          echo "Starting to compile..."
          if [[ "${{ matrix.build-type }}" == "mi8937" ]]; then
            ./build.sh msm8937-perf_defconfig msm8937/mi8937.config --ksu=KSU_BLXX
          elif [[ "${{ matrix.build-type }}" == "mi8917" ]]; then
            ./build.sh msm8937-perf_defconfig msm8937/mi8917.config --ksu=KSU_BLXX
          fi
          cd ..
          ls -la android_kernel_xiaomi_msm8937/out/arch/arm64/boot/

      - name: Preparing AnyKernel3 sources
        run: |
          if [ -d "$PWD/AnyKernel3" ]; then
            rm -rf AnyKernel3
          fi
          git clone https://github.com/riarumoda/AnyKernel3 AnyKernel3 --depth=1
          cp android_kernel_xiaomi_msm8937/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          if [[ "${{ matrix.build-type }}" == "mi8937" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
            sed -i 's/device.name1=sweet/device.name1=mi8937/' AnyKernel3/anykernel.sh
            sed -i 's/device.name2=sweetin/device.name2=santoni/' AnyKernel3/anykernel.sh
            sed -i '/device.name2=santoni/a device.name3=land\ndevice.name4=ugg' AnyKernel3/anykernel.sh
            sed -i 's/sweet (sm6150)/mi8937 (msm8937)/g' AnyKernel3/banner
          elif [[ "${{ matrix.build-type }}" == "mi8917" ]]; then
            sed -i 's/supported.versions=11-16/supported.versions=11-16/' AnyKernel3/anykernel.sh
            sed -i 's/device.name1=sweet/device.name1=mi8917/' AnyKernel3/anykernel.sh
            sed -i 's/device.name2=sweetin/device.name2=rolex/' AnyKernel3/anykernel.sh
            sed -i '/device.name2=rolex/a device.name3=riva\ndevice.name4=ugglite' AnyKernel3/anykernel.sh
            sed -i 's/sweet (sm6150)/mi8917 (msm8917)/g' AnyKernel3/banner
          fi

      - name: Pack & upload artifacts (All builds)
        uses: actions/upload-artifact@v6
        with:
          name: perf-neon-${{ matrix.build-type }}-testing-${{ steps.ts.outputs.DATE }}-${{ steps.ts.outputs.TIME }}
          path: |
            AnyKernel3/*
